version: "3.9"

services:
  mortgage-api:
    container_name: mortgage-api
    ports:
      - "3000:3000"
      - "5678:5678"
      - "9229:9229"
    build: .
    volumes:
      - .:/application
    command: sh -c "npm install && npm run start:local"
    working_dir: /application
    environment:
      PORT: "3000"
      PROPERTY_PRICE_MINIMUM_DOWN_PAYMENT: "0.2"
